adding exit if usbboot doesnt exist

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -2,9 +2,9 @@
 
 OKGREEN='\033[92m'
 # WARNING='\033[93m'
-FAIL='\033[91m'
-OKBLUE='\033[94m'
-UNDERLINE='\033[4m'
+# FAIL='\033[91m'
+# OKBLUE='\033[94m'
+# UNDERLINE='\033[4m'
 ENDC='\033[0m'
 
 echo "Installing dependancies ..."
@@ -15,6 +15,6 @@ echo "Preparing usbboot submodule ..."
 git submodule update --init --recursive
 echo "Syncing with usbboot remote"
 git submodule update --remote
-cd usbboot
+cd usbboot || exit
 make
 echo -e "${OKGREEN} ✓ ${ENDC} complete"
